### ISSUE TITLE
Consider using strict mode for mypy

### ISSUE THREAD

**Issue by Trombach** [UoA-eResearch/mytardis_ingestion#50]
see [docs](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-strict)

can be enabled in `pyproject.toml`:
```toml
[tool.mypy]
# ...
strict = true
```
